### ISSUE TITLE
Action.Muteaudio is not a constructor

### ISSUE THREAD

**Issue by JasonScopServ** [NumminorihSF/ami-io#11]
Having a problem where I tried to send a MuteAudio action to the AMI but fails with:

TypeError: amiio.Action.Muteaudio is not a constructor

The line that fails:

 var action = new amiio.Action.MuteAudio();

Any ideas?

**Comment by NumminorihSF** [comment]
The problem is that there is not such action in package. Now you can create this action by manual call main action constructor:
```
var action = new amiio.Action.Action('MuteAudio');
```

I'll update README and add some improvement for such case into library.

**Comment by JasonScopServ** [comment]
Thank you very much :+1:  It works.
