### ISSUE TITLE
How can I create new Actions and events without modifying the original package

### ISSUE THREAD

**Issue by raarts** [NumminorihSF/ami-io#3]
Also see this [stackoverflow question](http://stackoverflow.com/questions/36411332/modifying-some-features-in-a-public-npm-package): I've already succeeded in overloading the auth function, how can I overload the Login action (or create a new one), and in general create new Actions and Events?

I do not want to fork the original package for a few lines of code changes.

**Comment by NumminorihSF** [comment]
You can use:

```
var AmiIo = require('ami-io');
AmiIo.Action.Login = function NewConstructor(){}; //to override Login action
//new constructor shold extend AmiIo.Action.Action(actionName)
//and also, you can use
AmiIo.Action.SomeNewAction = function SomeNewAction(){};//to create new actuion
//it also should extend AmiIo.Action.Action(actionName);
```
AmiIo.Action is just an Object. All constructors are fields of it.

To create new events you don't need to do anything, because it is just an object. If server send to you
```
Event: Armageddon
SomeField: 123
```
ami-io will create event with name `'Armageddon'`.


To override Client#auth() method, you just should do
```
var AmiIo = require('ami-io');
AmiIo.Client.prototype.auth = function (){};//new function
```
