### ISSUE TITLE
use this in VueJs

### ISSUE THREAD

**Issue by msadeghyan1996** [NumminorihSF/ami-io#34]
hi. i have a question. can i use this package in vuejs?

**Comment by NumminorihSF** [comment]
Hi,
it's a server-side library. If you check the lib's code, you'll find that there is another nodejs' internal module (net), so I don't think it's easy to use this lib in browser.
And I also don't think that it's a good idea to send ami's creds to anyone's browser.

**Comment by msadeghyan1996** [comment]
thanks for fast replay.
i want show realtime ami data's on wallboard and use with pusher for show in vuejs. now i want give data's from ami-io module and send to vuejs for show in wallboard.
is it a good way for this work or no?
