### ISSUE TITLE
hide logger messages

### ISSUE THREAD

**Issue by ikerib** [NumminorihSF/ami-io#8]
Hi,
I want to print log info only when some events happen like this:
```

if ( event.event === 'Hangup') {
        console.log("Hangup");
        amiio.logger.info('event:', event);
    }
```

But is printing everything all the time... any help?

**Comment by NumminorihSF** [comment]
Hi. 
By default `amiio.logger` has very verbose log. To log only event you need, use `AmiIo.SilentLogger` as logger and do
```
amiio.on('event', eventObject => logOrFilterAsYouWhant(eventObject));
```

**Comment by ikerib** [comment]
Sorry, I'm quite new with node... can you extend your example?
What I want to log is all call send/received by extension

**Comment by NumminorihSF** [comment]
I updated example above.

**Comment by ikerib** [comment]
Thanks! Finally I've got it working with this code:
```
amiio.on('event', function(event){
    if (event.event === 'Hangup'){
        console.log('event:', event);
    }
    if (event.event === "Dial") {
        console.log("Ring Ring");
    }
});
```

With your code I had an error on this line:
`amiio.on('event', eventObject => logOrFilterAsYouWhant(eventObject));`

Expression expected on '=>'

**Comment by Seafnox** [comment]
@ikerib you need to use ES2015+ (node 4+) or use babel instead if you want work with array function.

**Comment by ikerib** [comment]
ok! thanks!
